/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week_01;

/**
 *
 * @author NITRO-5
 */
public class Frm_Playfair extends javax.swing.JFrame {

    /**
     * Creates new form Frm_railfe
     */
   private char[][] pf = new char[5][5];

    public Frm_Playfair() {
        initComponents();
    }
 private void taoMaTran(String khoa) {
        StringBuilder sb = new StringBuilder();
        boolean[] daXuatHien = new boolean[26]; 
        khoa = khoa.toUpperCase().replace('J', 'I'); 
        for (char c : khoa.toCharArray()) {
            if (c >= 'A' && c <= 'Z' && !daXuatHien[c - 'A']) {
                sb.append(c);
                daXuatHien[c - 'A'] = true;
            }
        }
        for (char c = 'A'; c <= 'Z'; c++) {
            if (c == 'J') continue; 
            if (!daXuatHien[c - 'A']) {
                sb.append(c);
            }
        }
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                pf[i][j] = sb.charAt(i * 5 + j);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_mahoa = new javax.swing.JButton();
        btn_giaima = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_vanban = new javax.swing.JTextArea();
        txt_khoa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_banma = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Chương trình Playfair");

        btn_mahoa.setText("Mã Hóa");
        btn_mahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mahoaActionPerformed(evt);
            }
        });

        btn_giaima.setText("Giải Mã");
        btn_giaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giaimaActionPerformed(evt);
            }
        });

        jLabel2.setText("VanBan");

        jLabel3.setText("Khoa");

        jLabel4.setText("Ban Ma");

        txt_vanban.setColumns(20);
        txt_vanban.setRows(5);
        jScrollPane1.setViewportView(txt_vanban);

        txt_banma.setColumns(20);
        txt_banma.setRows(5);
        jScrollPane2.setViewportView(txt_banma);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_mahoa)
                                        .addGap(28, 28, 28)
                                        .addComponent(btn_giaima))
                                    .addComponent(txt_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mahoa)
                    .addComponent(btn_giaima))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mahoaActionPerformed
        // TODO add your handling code here:
            String banro = this.txt_vanban.getText();
            String khoa = this.txt_khoa.getText(); 
            taoMaTran(khoa);
            banro = banro.toUpperCase();
            banro = banro.replace('J', 'I');
            String banma = mahoa(banro);
            this.txt_banma.setText(banma);

    }//GEN-LAST:event_btn_mahoaActionPerformed

    private void btn_giaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giaimaActionPerformed
        // TODO add your handling code here:
            String banma = this.txt_banma.getText();
            String khoa = this.txt_khoa.getText(); 
            taoMaTran(khoa); 
            banma = banma.toUpperCase();
            banma = banma.replace('J', 'I');
            String banro = giaima(banma);
            this.txt_vanban.setText(banro);
        
    }//GEN-LAST:event_btn_giaimaActionPerformed

  private String thaythe(char a, char b) {
        String vta = timViTri(a);
        String vtb = timViTri(b);
        char x, y;

        if (vta.charAt(0) == vtb.charAt(0)) {
            x = pf[vta.charAt(0) - '0'][((vta.charAt(1) - '0') + 1) % 5];
            y = pf[vtb.charAt(0) - '0'][((vtb.charAt(1) - '0') + 1) % 5];
            return x + "" + y;
        }

        if (vta.charAt(1) == vtb.charAt(1)) { 
            x = pf[((vta.charAt(0) - '0') + 1) % 5][vta.charAt(1) - '0'];
            y = pf[((vtb.charAt(0) - '0') + 1) % 5][vtb.charAt(1) - '0'];
            return x + "" + y;
        }

        x = pf[vta.charAt(0) - '0'][vtb.charAt(1) - '0'];
        y = pf[vtb.charAt(0) - '0'][vta.charAt(1) - '0'];
        return x + "" + y;
    }
 private String timViTri(char a) {
        for (int i = 0; i < 5; i++)
            for (int j = 0; j < 5; j++)
                if (pf[i][j] == a)
                    return i + "" + j;
        return "";}
    
private String thaytheNguoc(char a, char b) {
    String vta = timViTri(a);
    String vtb = timViTri(b);
    char x, y;

    if (vta.charAt(0) == vtb.charAt(0)) {
        x = pf[vta.charAt(0) - '0'][((vta.charAt(1) - '0') + 4) % 5];
        y = pf[vtb.charAt(0) - '0'][((vtb.charAt(1) - '0') + 4) % 5]; 
        return x + "" + y;
    }
    
    if (vta.charAt(1) == vtb.charAt(1)) { 
        x = pf[((vta.charAt(0) - '0') + 4) % 5][vta.charAt(1) - '0']; 
        y = pf[((vtb.charAt(0) - '0') + 4) % 5][vtb.charAt(1) - '0']; 
        return x + "" + y;
    }

    x = pf[vta.charAt(0) - '0'][vtb.charAt(1) - '0'];
    y = pf[vtb.charAt(0) - '0'][vta.charAt(1) - '0'];
    return x + "" + y;
}
private String mahoa(String banro){
        int n = banro.length();
        int i = 0;
        String banma = "";
        char a, b;

        while (i < n) {
            if (i == n - 1) {
                a = banro.charAt(i);
                b = 'X'; 
                i++;
            } else {
                a = banro.charAt(i);
                b = banro.charAt(i + 1);
                if (a == b) {
                    b = 'X';
                    i++;
                } else {
                    i += 2;
                }
            }
            banma += thaythe(a, b);
        }
        return banma;
    }
  private String giaima(String banma) {
    int n = banma.length();
    StringBuilder banro = new StringBuilder();
    char a, b;

    for (int i = 0; i < n; ) {
        if (i == n - 1) { 
            a = banma.charAt(i);
            banro.append(a);
            break;
        } else {
            a = banma.charAt(i);
            b = banma.charAt(i + 1);
            banro.append(thaytheNguoc(a, b)); 
            i += 2; 
        }
    }
    return banro.toString();
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Playfair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Playfair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Playfair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Playfair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Playfair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giaima;
    private javax.swing.JButton btn_mahoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_banma;
    private javax.swing.JTextField txt_khoa;
    private javax.swing.JTextArea txt_vanban;
    // End of variables declaration//GEN-END:variables
}
